[project]
name = "py-backend"
version = "0.1.0"
description = "A custom build backend"
readme = "README.md"
requires-python = ">=3.11"
dependencies = []

[build-system]
requires = []
build-backend = "build_backend"
backend-path = ["."]
